### ISSUE TITLE
Colorpalette9

### ISSUE THREAD

**Issue by friosavila** [benjann/palettes#2]
Dear Ben,
I was playing a bit with colorpalette9 (with Stata 12), to check some backward compatibility with some plot programs I'm working with.
I wanted to ask about a possible bug.
When I use a custom palette defined by the following program:
```
program colorpalette9_redox2 
     c_local P #2e5894, #ffe733, #ffb200, #ec5800, #96001b 
end 
```
and I try to use interpolation, but it doesn't seem to work:

```
colorpalette9 redox2, 
colorpalette9 redox2, n(10)  // Produces the same as above
```

Perhaps I need to add something else to the program?
Thank you
Fernando

**Comment by benjann** [comment]
Hi Fernando, this is not a bug. Essentially, `colorpalette9` is a snapshot of `colorpalette` before I upgraded `colorpalette` to make used of `ColrSpace` (which requires Stata 14). At that time `n()` did not apply automatic interpolation; this is consistent with the description in `help colorpalette9`. The automatic interpolation stuff has been added to `colorpalette` at some later point. I keep `colorpalette9` in the distribution so users of Stata version prior to version 14 do not lose functionality they once had (i.e. before `colorpalette` was upgraded), but my intention is not to expand functionality for these users. It would be too much work for me to keep on developing both, `colorpalette9` and `colorpalette` (but of course I will still try to fix bugs in `colorpalette9` once they pop up). I hope you understand.

In your example, you could type:
```Stata
colorpalette9 redox2, ipolate(10)
```
ben

**Comment by friosavila** [comment]
Thank you Ben
That is good to know.
Btw I really like color palette. Now that I got a hand of it I’m trying to
use it more on some plot  commands I’m working on.
Thanks again for your help, and giving me the tip on ipolate()
Best wishes
Fernando
