### ISSUE TITLE
Issue installing package

### ISSUE THREAD

**Issue by michelemary97** [benjann/palettes#3]
Hi Ben, 
I was attempting to re-install palettes to check a package setup dofile for a project and had this error show up. I last ran this do file a week ago and palettes was installed without issue. I also asked a colleague who did not have palettes installed prior to try and it showed the same error. Do you know what the issue might be? Thanks!
![Screen Shot 2023-12-11 at 4 54 50 PM](https://github.com/benjann/palettes/assets/88711934/a74803b3-6dd5-4418-92d3-7570291a3892)

**Comment by benjann** [comment]
Hi, thanks for reporting the problem. I forwarded this to Kit Baum (maintainer of the SSC Archive) so he can fix the problem. ben

**Comment by benjann** [comment]
The problem should now be fixed.
